import os

# base.pkl 位置
SOURCE_DIR = os.path.dirname(os.path.abspath(__file__))
TRADING_BASE_PICKLE_DIR = os.path.join(SOURCE_DIR,"base.pkl")
FUTURE_CONTRACT_INFO_PICKLE_DIR = os.path.join(SOURCE_DIR,"FutureContractInfo.pkl")

# 默认票池
DEFAULT_SPOT_SYMBOLS = ['SHIBUSDT', 'XECUSDT','AAVEUSDT', 'ADAUSDT', 'ALGOUSDT', 'ARUSDT', 'ATOMUSDT', 'AUDIOUSDT', 'AVAXUSDT', 'AXSUSDT', 'BATUSDT', 'BCHUSDT', 'BNBUSDT', 'BTCUSDT', 'CELOUSDT', 'CHZUSDT', 'COMPUSDT', 'CRVUSDT', 'DASHUSDT', 'DOGEUSDT', 'DOTUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ETCUSDT', 'ETHUSDT', 'FILUSDT', 'FTMUSDT', 'GALAUSDT', 'GRTUSDT', 'HBARUSDT', 'HNTUSDT', 'HOTUSDT', 'ICPUSDT', 'ICXUSDT', 'IOTXUSDT', 'KLAYUSDT', 'KSMUSDT', 'LINKUSDT', 'LRCUSDT', 'LTCUSDT', 'LUNAUSDT', 'MANAUSDT', 'MATICUSDT', 'MKRUSDT', 'NEARUSDT', 'NEOUSDT', 'OMGUSDT', 'ONEUSDT', 'QTUMUSDT', 'RENUSDT', 'RUNEUSDT', 'RVNUSDT', 'SANDUSDT', 'SNXUSDT', 'SOLUSDT', 'SUSHIUSDT', 'THETAUSDT', 'TRXUSDT', 'UNIUSDT', 'VETUSDT', 'WAVESUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'YFIUSDT', 'ZECUSDT', 'ZILUSDT']
DEFAULT_FUTURE_SYMBOLS = ['1000SHIBUSDT', '1000XECUSDT','AAVEUSDT', 'ADAUSDT', 'ALGOUSDT', 'ARUSDT', 'ATOMUSDT', 'AUDIOUSDT', 'AVAXUSDT', 'AXSUSDT', 'BATUSDT', 'BCHUSDT', 'BNBUSDT', 'BTCUSDT', 'CELOUSDT', 'CHZUSDT', 'COMPUSDT', 'CRVUSDT', 'DASHUSDT', 'DOGEUSDT', 'DOTUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ETCUSDT', 'ETHUSDT', 'FILUSDT', 'FTMUSDT', 'GALAUSDT', 'GRTUSDT', 'HBARUSDT', 'HNTUSDT', 'HOTUSDT', 'ICPUSDT', 'ICXUSDT', 'IOTXUSDT', 'KLAYUSDT', 'KSMUSDT', 'LINKUSDT', 'LRCUSDT', 'LTCUSDT', 'LUNAUSDT', 'MANAUSDT', 'MATICUSDT', 'MKRUSDT', 'NEARUSDT', 'NEOUSDT', 'OMGUSDT', 'ONEUSDT', 'QTUMUSDT', 'RENUSDT', 'RUNEUSDT', 'RVNUSDT', 'SANDUSDT', 'SNXUSDT', 'SOLUSDT', 'SUSHIUSDT', 'THETAUSDT', 'TRXUSDT', 'UNIUSDT', 'VETUSDT', 'WAVESUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'YFIUSDT', 'ZECUSDT', 'ZILUSDT']

# BTTUSDT, '1000SHIBUSDT', '1000XECUSDT' 暂时被排除因为不在base里

# Simulator 才用的设置
# DS位置
DS_PACKAGE_PATH = "/home/mark/alpha_dataserver/"
# Basic data位置
data_tag = "AlphaY2021V2"
BASIC_DATA_PATH = f"/mnt3/basic_data_{data_tag}"